name: Production
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 部署到服务器
      - name: Deploy
        uses: appleboy/ssh-action@master # 使用ssh链接服务器
        with:
          host: ${{ secrets.SSH_HOST }} #配置的服务器地址
          username: ${{ secrets.SSH_USERNAME }} #配置的服务器用户名
          password: ${{ secrets.SSH_PASSWORD }} #配置的密码
          port: ${{ secrets.SSH_PORT }}
          script:
            | # 执行命令（运行到服务器）cd：要确保服务器有这个目录； wget：下载上一步的build文件到服务器； tar：解压； 安装依赖；启动服务 npm: 安装包/build项目
            cd /root/summer
            wget https://github.com/graywenn/summer/archive/${{github.ref}}.tar.gz -O ${{github.ref_name}}.tar.gz
            tar zxvf ${{github.ref_name}}.tar.gz --strip-components 1
            npm i
            npm run build
